apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  project: default
  destination:
    name: in-cluster
    namespace: prometheus
  source:
    repoURL: https://github.com/amoravek/k8s-datascript.git
    targetRevision: HEAD
    path: argo-model/prometheus
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
