apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  labels:
    cluster: in-cluster
    app: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amoravek/k8s-datascript.git
    targetRevision: HEAD
    path: apps
  destination:
    name: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
